services:
  - type: web
    name: attendance-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn ATTENDANCE.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString

databases:
  - name: attendance-db
    plan: free